name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run Python tests
        run: |
          # Ensure directories are treated as packages
          touch src/lambda/__init__.py
          touch tests/__init__.py
          export PYTHONPATH="${PYTHONPATH}:${PWD}/src/lambda:${PWD}"
          python -m pytest tests/ -v

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy infrastructure with Terraform
        run: |
          cd terraform
          terraform init -input=false
          terraform validate
          terraform plan -out=tfplan -input=false
          terraform apply -input=false -auto-approve tfplan
