name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run Python tests
        run: |
          touch src/lambda/__init__.py
          touch tests/__init__.py
          export PYTHONPATH="${PYTHONPATH}:${PWD}/src/lambda:${PWD}"
          python -m pytest tests/ -v

  terraform-plan:
    needs: tests
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::205930604749:role/GithubActionsRole
          role-session-name: github-actions
          aws-region: us-west-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5

      - name: Terraform plan (preview only)
        run: |
          cd terraform
          terraform init -input=false
          terraform validate
          terraform plan -input=false

  terraform-apply:
    needs: tests
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::205930604749:role/GithubActionsRole
          role-session-name: github-actions
          aws-region: us-west-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5

      - name: Terraform apply (deploy)
        run: |
          cd terraform
          terraform init -input=false
          terraform validate
          terraform plan -out=tfplan -input=false
          terraform apply -input=false -auto-approve tfplan
